### ISSUE TITLE
CURA_CONFIGS issue.

### ISSUE THREAD

**Issue by rovermeyer** [DA-Osborne/Spool-Maker#11]
I'm not sure if this is a common problem or just on my system.  I ran spoolmaker several weeks ago and it worked.  After upgrading Cura to V5.4.0, I get the following error.  I also downloaded the newest version of Spoolmaker today and I get the same error. 

        Traceback (most recent call last):
          File "C:******\SpoolMaker.py", line 35, in <module>
            import CuraMaterial as c
          File "C:******\CuraMaterial.py", line 58, in <module>
            CURA_CONFIGS.sort(key=lambda x:int(x.replace(".","" if len(x)>3 else "0")))
          File "C:******\CuraMaterial.py", line 58, in <lambda>
            CURA_CONFIGS.sort(key=lambda x:int(x.replace(".","" if len(x)>3 else "0")))
        ValueError: invalid literal for int() with base 10: 'storage'

So I inserted a print statement to show CURA_CONFIGS.  

        CURA_CONFIGS =   ['3.6', '4.0', '4.1', '4.10', '4.11', '4.12', '4.13', '4.2', '4.3', '4.4', 
        '4.5', '4.6', '4.7', '4.8', '4.9', '5.0', '5.1', '5.2', '5.4', 'storage']

I deleted the last item in the list and the program now runs.

        CURA_CONFIGS = [f.name for f in os.scandir(CURA_USER_DIR) if f.is_dir()]
        del CURA_CONFIGS[-1]
      

Nice program.  Thanks.
      
Bob O.

**Comment by Monroe07** [comment]
I made a pull request to address the removal of all non-numbers values from the CURA_CONFIGS list. Its [here](https://github.com/DA-Osborne/Spool-Maker/pull/13/files)

**Comment by DA-Osborne** [comment]
I merged the pull request as this solves the issue.
